server:
    port: 2020

spring:
  profiles:
    active: dev
  application:
      name: recognize-service

---
# dev
spring:
  profiles: dev
liumapp:
  filemanager:
    savePath: /usr/local/tomcat/project/recognize-face-by-idcard/data/
  recognize:
    baidu:
      appId: your_appId_here
      appKey: your_appKey_here
      appSecret: your_appSecret_here

---
# docker
spring:
  profiles: docker
liumapp:
  filemanager:
    savePath: /recognize-face-by-idcard/data/
  recognize:
    baidu:
      appId: your_appId_here
      appKey: your_appKey_here
      appSecret: your_appSecret_here
